### ISSUE TITLE
no header on smartphone

### ISSUE THREAD

**Issue by bulton-fr** [bulton-fr/twitzer-timeline#6]
The application cannot be used on smartphone because no header is displayed (so no auth or load button)

```css
@media screen and (max-width: 1024px)
<style>…</style>
.mdl-layout__header {
    display: none;
}
```
